language: ruby
script: rake ci
rvm:
  - 2.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2
  - rbx-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-head
